[package]
name = "clickr"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
actix-ws = "0.3.0"
clap = { version = "4.5.29", features = ["derive"] }
env_logger = "0.11.6"
futures = "0.3.31"
log = "0.4.25"
serde = "1.0.217"
shellexpand = "3.1.0"
